name: Cypress Tests

on:
  workflow_dispatch:
  push:
    branches: [develop]

jobs:
  cypress:
    name: Run Cypress Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: yarn install

      - name: Build Application
        run: yarn build-and-start

      - name: Start Application for E2E Tests
        run: |
          docker-compose -f docker-compose.test.yml up -d
          echo "Application started for E2E tests."

      - name: Run Cypress Tests
        run: yarn cypress:run
        env:
          CI: true

      - name: Stop and Clean Up After Tests
        if: always()
        run: docker-compose -f docker-compose.test.yml down
