name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [develop]

env:
  DOCKER_IMAGE: nmd-admin-ui:${{ github.sha }}
  CONTAINER_NAME: nmd-admin-ui
  AWS_DEFAULT_REGION: ap-southeast-1

jobs:
  pack:
    name: Build, test, and deploy Docker Image
    runs-on: ubuntu-latest
    env:  # Bổ sung các biến môi trường cho job
      NEXT_PUBLIC_BASE_URL: http://localhost:3000/api
      PROXY_BACKEND: https://backend.helenspeaking.com/api/v1
    steps:
      - uses: actions/checkout@v2  # Checkout mã nguồn

      # Thiết lập Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      # Cài đặt dependencies
      - name: Install Dependencies
        run: yarn install

      # Build ứng dụng
      - name: Build Application
        run: yarn build-and-start

      # Kiểm tra ứng dụng (chạy Cypress)
      - name: Run Cypress Tests
        run: yarn cypress:run

      # Build Docker image
      - name: Build Docker Image
        run: sudo docker build --no-cache -t ${{ env.DOCKER_IMAGE }} .

      # Kiểm tra container hiện tại
      - name: Check if Container Exists
        run: |
          CONTAINER_ID=$(sudo docker ps -a -q -f name=^${{ env.CONTAINER_NAME }})
          if [ "$CONTAINER_ID" ]; then
            echo "Container ${{ env.CONTAINER_NAME }} exists with ID $CONTAINER_ID, removing it..."
            sudo docker rm -f $CONTAINER_ID
            echo "Container ${{ env.CONTAINER_NAME }} removed."
          else
            echo "Container ${{ env.CONTAINER_NAME }} does not exist."
          fi

      # Deploy container
      - name: Deploy to AWS
        run: |
          echo "Creating and starting container ${{ env.CONTAINER_NAME }}..."
          sudo docker create --restart unless-stopped -p 3007:3000 --name ${{ env.CONTAINER_NAME }} ${{ env.DOCKER_IMAGE }}
          sudo docker start ${{ env.CONTAINER_NAME }}
          echo "Container ${{ env.CONTAINER_NAME }} started with image ${{ env.DOCKER_IMAGE }}."

      # Dọn dẹp tài nguyên Docker
      - name: Clean up
        run: |
          echo "Cleaning up dangling images and containers..."
          yes | sudo docker image prune -f
          yes | sudo docker container prune -f
          sudo docker images -q --filter "dangling=true" | xargs -r sudo docker rmi -f
          yes | sudo docker system prune --all -f
