name: Deploy
on:
  workflow_dispatch:
  push:
    branches: [develop]

env:
  DOCKER_IMAGE: nmd-admin-ui:${{ github.sha }}
  CONTAINER_NAME: nmd-admin-ui
  AWS_DEFAULT_REGION: ap-southeast-1

jobs:
  test:
    name: Run Cypress Tests
    runs-on: ubuntu-latest  # Thay vì [self-hosted]
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          
      - name: Install Dependencies
        run: yarn add next@14.0.3

      - name: Build and Start Application
        run: yarn build-and-start &
        
      - name: Wait for App to Start
        run: |
          echo "Waiting for app to start..."
          sleep 30  # Adjust this value based on your app's startup time

      - name: Run Cypress Tests
        run: yarn cypress:run  # Note: Using cypress:run instead of cypress:open for CI

  pack:
    name: Build and deploy Docker Image
    needs: test  # This ensures tests pass before deploying
    runs-on: ubuntu-latest  # Thay vì [self-hosted]
    steps:
      - uses: actions/checkout@v2

      - name: Build Docker Image
        run: sudo docker build --no-cache -t ${{ env.DOCKER_IMAGE }} .

      - name: Check if Container Exists
        run: |
          CONTAINER_ID=$(sudo docker ps -a -q -f name=^${{ env.CONTAINER_NAME }})
          if [ "$CONTAINER_ID" ]; then
            echo "Container ${{ env.CONTAINER_NAME }} exists with ID $CONTAINER_ID, removing it..."
            sudo docker rm -f $CONTAINER_ID
            echo "Container ${{ env.CONTAINER_NAME }} removed."
          else
            echo "Container ${{ env.CONTAINER_NAME }} does not exist."
          fi

      - name: Deploy to AWS
        run: |
          echo "Creating and starting container ${{ env.CONTAINER_NAME }}..."
          sudo docker create --restart unless-stopped -p 3007:3000 --name ${{ env.CONTAINER_NAME }} ${{ env.DOCKER_IMAGE }}
          sudo docker start ${{ env.CONTAINER_NAME }}
          echo "Container ${{ env.CONTAINER_NAME }} started with image ${{ env.DOCKER_IMAGE }}."

      - name: Clean up
        run: |
          echo "Cleaning up dangling images and containers..."
          yes | sudo docker image prune -f
          yes | sudo docker container prune -f
          sudo docker images -q --filter "dangling=true" | xargs -r sudo docker rmi -f
          yes | sudo docker system prune --all -f